import {
  Account,
  Category,
  Family,
  FamilyMember,
  Goal,
  Budget,
  Transaction,
  UserProfile,
  Transfer,
  RecurringTransaction,
  TransactionTemplate,
  NotificationItem,
  NotificationPreferences,
  FamilyActivityItem,
  Plan,
  Subscription,
  FinancialProfile,
  AiUsageRecord,
} from '../types';

export const DEMO_PROFILES: UserProfile[] = [
  {
    id: 'user-andi-01',
    full_name: 'Andi Pratama',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'user-sinta-02',
    full_name: 'Sinta Dewi',
    avatar_url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    created_at: '2026-08-02T00:00:00Z',
  },
];

export const DEMO_FAMILY: Family = {
  id: 'fam-bahagia-01',
  name: 'Keluarga Bahagia',
  invite_code: 'LEGAKU-AB12CD',
  created_by: 'user-andi-01',
  created_at: '2026-08-01T00:00:00Z',
  updated_at: '2026-08-01T00:00:00Z',
};

export const DEMO_FAMILY_MEMBERS: FamilyMember[] = [
  {
    id: 'mem-01',
    family_id: 'fam-bahagia-01',
    user_id: 'user-andi-01',
    role: 'owner',
    joined_at: '2026-08-01T00:00:00Z',
    profile: DEMO_PROFILES[0],
  },
  {
    id: 'mem-02',
    family_id: 'fam-bahagia-01',
    user_id: 'user-sinta-02',
    role: 'partner',
    joined_at: '2026-08-03T00:00:00Z',
    profile: DEMO_PROFILES[1],
  },
];

export const DEFAULT_CATEGORIES: Category[] = [
  // Expense
  { id: 'cat-exp-1', family_id: null, name: 'Makan & Minum', type: 'expense', icon: 'Utensils', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-exp-2', family_id: null, name: 'Rumah Tangga', type: 'expense', icon: 'Home', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-exp-3', family_id: null, name: 'Transportasi', type: 'expense', icon: 'Car', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-exp-4', family_id: null, name: 'Pendidikan', type: 'expense', icon: 'GraduationCap', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-exp-5', family_id: null, name: 'Kesehatan', type: 'expense', icon: 'HeartPulse', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-exp-6', family_id: null, name: 'Belanja', type: 'expense', icon: 'ShoppingBag', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-exp-7', family_id: null, name: 'Tagihan', type: 'expense', icon: 'Receipt', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-exp-8', family_id: null, name: 'Hiburan', type: 'expense', icon: 'Gamepad2', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-exp-9', family_id: null, name: 'Keluarga', type: 'expense', icon: 'Users', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-exp-10', family_id: null, name: 'Lainnya', type: 'expense', icon: 'MoreHorizontal', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  
  // Income
  { id: 'cat-inc-1', family_id: null, name: 'Gaji', type: 'income', icon: 'Briefcase', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-inc-2', family_id: null, name: 'Bisnis', type: 'income', icon: 'Store', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-inc-3', family_id: null, name: 'Freelance', type: 'income', icon: 'Laptop', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-inc-4', family_id: null, name: 'Bonus', type: 'income', icon: 'Gift', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-inc-5', family_id: null, name: 'Investasi', type: 'income', icon: 'TrendingUp', is_default: true, created_at: '2026-01-01T00:00:00Z' },
  { id: 'cat-inc-6', family_id: null, name: 'Lainnya', type: 'income', icon: 'PlusCircle', is_default: true, created_at: '2026-01-01T00:00:00Z' },
];

export const DEMO_ACCOUNTS: Account[] = [
  {
    id: 'acc-bca-01',
    family_id: 'fam-bahagia-01',
    name: 'BCA Utama',
    type: 'bank',
    initial_balance: 10000000,
    current_balance: 14500000,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-09-20T00:00:00Z',
  },
  {
    id: 'acc-mandiri-02',
    family_id: 'fam-bahagia-01',
    name: 'Mandiri Tabungan',
    type: 'bank',
    initial_balance: 2000000,
    current_balance: 5000000,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-09-20T00:00:00Z',
  },
  {
    id: 'acc-gopay-03',
    family_id: 'fam-bahagia-01',
    name: 'GoPay Bersama',
    type: 'ewallet',
    initial_balance: 500000,
    current_balance: 850000,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-09-20T00:00:00Z',
  },
  {
    id: 'acc-cash-04',
    family_id: 'fam-bahagia-01',
    name: 'Dompet Tunai',
    type: 'cash',
    initial_balance: 400000,
    current_balance: 650000,
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-09-20T00:00:00Z',
  },
];

// Helper to get today's date formatted YYYY-MM-DD
const today = new Date();
const formatDateOffset = (daysOffset: number): string => {
  const d = new Date();
  d.setDate(today.getDate() - daysOffset);
  return d.toISOString().split('T')[0];
};

export const DEMO_TRANSACTIONS: Transaction[] = [
  {
    id: 'tx-01',
    family_id: 'fam-bahagia-01',
    account_id: 'acc-gopay-03',
    category_id: 'cat-exp-1',
    type: 'expense',
    amount: 150000,
    transaction_date: formatDateOffset(0),
    description: 'Makan malam sate & es kelapa',
    notes: 'Makan malam santai bersama anak-anak',
    source: 'manual',
    created_by: 'user-andi-01',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    account_name: 'GoPay Bersama',
    category_name: 'Makan & Minum',
    category_icon: 'Utensils',
    creator_name: 'Andi Pratama',
  },
  {
    id: 'tx-02',
    family_id: 'fam-bahagia-01',
    account_id: 'acc-bca-01',
    category_id: 'cat-exp-6',
    type: 'expense',
    amount: 320000,
    transaction_date: formatDateOffset(0),
    description: 'Belanja mingguan buah & susu',
    notes: 'Superindo',
    source: 'manual',
    created_by: 'user-sinta-02',
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 3600000 * 3).toISOString(),
    account_name: 'BCA Utama',
    category_name: 'Belanja',
    category_icon: 'ShoppingBag',
    creator_name: 'Sinta Dewi',
  },
  {
    id: 'tx-03',
    family_id: 'fam-bahagia-01',
    account_id: 'acc-cash-04',
    category_id: 'cat-exp-3',
    type: 'expense',
    amount: 50000,
    transaction_date: formatDateOffset(1),
    description: 'Bensin motor & parkir',
    source: 'manual',
    created_by: 'user-andi-01',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    account_name: 'Dompet Tunai',
    category_name: 'Transportasi',
    category_icon: 'Car',
    creator_name: 'Andi Pratama',
  },
  {
    id: 'tx-04',
    family_id: 'fam-bahagia-01',
    account_id: 'acc-bca-01',
    category_id: 'cat-exp-7',
    type: 'expense',
    amount: 685000,
    transaction_date: formatDateOffset(2),
    description: 'Listrik PLN & WiFi Indihome',
    notes: 'Tagihan bulanan rumah',
    source: 'manual',
    created_by: 'user-andi-01',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    account_name: 'BCA Utama',
    category_name: 'Tagihan',
    category_icon: 'Receipt',
    creator_name: 'Andi Pratama',
  },
  {
    id: 'tx-05',
    family_id: 'fam-bahagia-01',
    account_id: 'acc-mandiri-02',
    category_id: 'cat-inc-3',
    type: 'income',
    amount: 4500000,
    transaction_date: formatDateOffset(3),
    description: 'Pembayaran Project Web Design',
    notes: 'Klien Studio Kreatif',
    source: 'manual',
    created_by: 'user-sinta-02',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    account_name: 'Mandiri Tabungan',
    category_name: 'Freelance',
    category_icon: 'Laptop',
    creator_name: 'Sinta Dewi',
  },
  {
    id: 'tx-06',
    family_id: 'fam-bahagia-01',
    account_id: 'acc-bca-01',
    category_id: 'cat-inc-1',
    type: 'income',
    amount: 15000000,
    transaction_date: formatDateOffset(15),
    description: 'Gaji Bulanan Kantor',
    source: 'manual',
    created_by: 'user-andi-01',
    created_at: new Date(Date.now() - 86400000 * 15).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 15).toISOString(),
    account_name: 'BCA Utama',
    category_name: 'Gaji',
    category_icon: 'Briefcase',
    creator_name: 'Andi Pratama',
  },
  {
    id: 'tx-07',
    family_id: 'fam-bahagia-01',
    account_id: 'acc-bca-01',
    category_id: 'cat-exp-2',
    type: 'expense',
    amount: 1250000,
    transaction_date: formatDateOffset(12),
    description: 'Belanja bulanan sembako & sabun',
    source: 'manual',
    created_by: 'user-sinta-02',
    created_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    updated_at: new Date(Date.now() - 86400000 * 12).toISOString(),
    account_name: 'BCA Utama',
    category_name: 'Rumah Tangga',
    category_icon: 'Home',
    creator_name: 'Sinta Dewi',
  },
];

export const DEMO_GOALS: Goal[] = [
  {
    id: 'goal-01',
    family_id: 'fam-bahagia-01',
    name: 'Dana Darurat 6 Bulan',
    target_amount: 30000000,
    current_amount: 18000000,
    target_date: '2026-12-31',
    description: 'Pondasi keamanan finansial keluarga untuk kebutuhan mendesak.',
    created_by: 'user-andi-01',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-09-15T00:00:00Z',
  },
  {
    id: 'goal-02',
    family_id: 'fam-bahagia-01',
    name: 'Liburan Keluarga Akhir Tahun',
    target_amount: 15000000,
    current_amount: 7500000,
    target_date: '2026-12-20',
    description: 'Rencana perjalanan bersama anak-anak ke Yogyakarta.',
    created_by: 'user-sinta-02',
    created_at: '2026-08-05T00:00:00Z',
    updated_at: '2026-09-10T00:00:00Z',
  },
];

const currentMonth = new Date().getMonth() + 1;
const currentYear = new Date().getFullYear();

export const DEMO_BUDGETS: Budget[] = [
  {
    id: 'bgt-01',
    family_id: 'fam-bahagia-01',
    category_id: 'cat-exp-1',
    amount: 3500000,
    month: currentMonth,
    year: currentYear,
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-09-01T00:00:00Z',
    category_name: 'Makan & Minum',
    category_icon: 'Utensils',
  },
  {
    id: 'bgt-02',
    family_id: 'fam-bahagia-01',
    category_id: 'cat-exp-2',
    amount: 3000000,
    month: currentMonth,
    year: currentYear,
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-09-01T00:00:00Z',
    category_name: 'Rumah Tangga',
    category_icon: 'Home',
  },
  {
    id: 'bgt-03',
    family_id: 'fam-bahagia-01',
    category_id: 'cat-exp-3',
    amount: 1500000,
    month: currentMonth,
    year: currentYear,
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-09-01T00:00:00Z',
    category_name: 'Transportasi',
    category_icon: 'Car',
  },
  {
    id: 'bgt-04',
    family_id: 'fam-bahagia-01',
    category_id: 'cat-exp-7',
    amount: 1200000,
    month: currentMonth,
    year: currentYear,
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-09-01T00:00:00Z',
    category_name: 'Tagihan',
    category_icon: 'Receipt',
  },
  {
    id: 'bgt-05',
    family_id: 'fam-bahagia-01',
    category_id: 'cat-exp-8',
    amount: 800000,
    month: currentMonth,
    year: currentYear,
    created_at: '2026-09-01T00:00:00Z',
    updated_at: '2026-09-01T00:00:00Z',
    category_name: 'Hiburan',
    category_icon: 'Gamepad2',
  },
];

// ----------------------------------------------------------------------------
// Phase 3 Demo Data
// ----------------------------------------------------------------------------

export const DEMO_TRANSFERS: Transfer[] = [
  {
    id: 'trf-01',
    family_id: 'fam-bahagia-01',
    from_account_id: 'acc-bca-01',
    to_account_id: 'acc-gopay-03',
    amount: 500000,
    transfer_date: formatDateOffset(1),
    description: 'Top-up GoPay untuk ongkos & jajan',
    created_by: 'user-andi-01',
    created_at: new Date(Date.now() - 86400000).toISOString(),
    updated_at: new Date(Date.now() - 86400000).toISOString(),
    from_account_name: 'BCA Utama',
    to_account_name: 'GoPay Bersama',
    creator_name: 'Andi Pratama',
  },
  {
    id: 'trf-02',
    family_id: 'fam-bahagia-01',
    from_account_id: 'acc-mandiri-02',
    to_account_id: 'acc-cash-04',
    amount: 300000,
    transfer_date: formatDateOffset(4),
    description: 'Tarik tunai untuk belanja pasar',
    created_by: 'user-sinta-02',
    created_at: new Date(Date.now() - 345600000).toISOString(),
    updated_at: new Date(Date.now() - 345600000).toISOString(),
    from_account_name: 'Mandiri Tabungan',
    to_account_name: 'Dompet Tunai',
    creator_name: 'Sinta Dewi',
  },
];

export const DEMO_RECURRING_TRANSACTIONS: RecurringTransaction[] = [
  {
    id: 'rec-01',
    family_id: 'fam-bahagia-01',
    type: 'expense',
    amount: 350000,
    description: 'Internet Rumah & Wifi Fiber',
    category_id: 'cat-exp-7',
    account_id: 'acc-bca-01',
    frequency: 'monthly',
    interval_value: 1,
    next_occurrence: formatDateOffset(-1), // Tomorrow or near due
    end_date: null,
    is_active: true,
    auto_create: false,
    created_by: 'user-andi-01',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    category_name: 'Tagihan',
    category_icon: 'Receipt',
    account_name: 'BCA Utama',
  },
  {
    id: 'rec-02',
    family_id: 'fam-bahagia-01',
    type: 'expense',
    amount: 500000,
    description: 'Token Listrik PLN',
    category_id: 'cat-exp-7',
    account_id: 'acc-bca-01',
    frequency: 'monthly',
    interval_value: 1,
    next_occurrence: formatDateOffset(-8),
    end_date: null,
    is_active: true,
    auto_create: false,
    created_by: 'user-sinta-02',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    category_name: 'Tagihan',
    category_icon: 'Receipt',
    account_name: 'BCA Utama',
  },
  {
    id: 'rec-03',
    family_id: 'fam-bahagia-01',
    type: 'income',
    amount: 18000000,
    description: 'Gaji Bulanan Kantor',
    category_id: 'cat-inc-1',
    account_id: 'acc-bca-01',
    frequency: 'monthly',
    interval_value: 1,
    next_occurrence: formatDateOffset(-5),
    end_date: null,
    is_active: true,
    auto_create: false,
    created_by: 'user-andi-01',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
    category_name: 'Gaji',
    category_icon: 'Briefcase',
    account_name: 'BCA Utama',
  },
];

export const DEMO_TEMPLATES: TransactionTemplate[] = [
  {
    id: 'tpl-01',
    family_id: 'fam-bahagia-01',
    name: '🍚 Makan Siang',
    type: 'expense',
    default_amount: 45000,
    category_id: 'cat-exp-1',
    account_id: 'acc-gopay-03',
    description: 'Makan siang harian',
    category_name: 'Makan & Minum',
    category_icon: 'Utensils',
    account_name: 'GoPay Bersama',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'tpl-02',
    family_id: 'fam-bahagia-01',
    name: '🛒 Belanja Bulanan',
    type: 'expense',
    default_amount: 350000,
    category_id: 'cat-exp-2',
    account_id: 'acc-bca-01',
    description: 'Belanja kebutuhan dapur & supermarket',
    category_name: 'Rumah Tangga',
    category_icon: 'Home',
    account_name: 'BCA Utama',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'tpl-03',
    family_id: 'fam-bahagia-01',
    name: '⛽ Bensin Motor',
    type: 'expense',
    default_amount: 35000,
    category_id: 'cat-exp-3',
    account_id: 'acc-cash-04',
    description: 'Isi bensin motor harian',
    category_name: 'Transportasi',
    category_icon: 'Car',
    account_name: 'Dompet Tunai',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'tpl-04',
    family_id: 'fam-bahagia-01',
    name: '💡 Token Listrik',
    type: 'expense',
    default_amount: 200000,
    category_id: 'cat-exp-7',
    account_id: 'acc-bca-01',
    description: 'Isi ulang token listrik rumah',
    category_name: 'Tagihan',
    category_icon: 'Receipt',
    account_name: 'BCA Utama',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
  {
    id: 'tpl-05',
    family_id: 'fam-bahagia-01',
    name: '📱 Paket Data & Wifi',
    type: 'expense',
    default_amount: 100000,
    category_id: 'cat-exp-7',
    account_id: 'acc-gopay-03',
    description: 'Paket data internet bulanan',
    category_name: 'Tagihan',
    category_icon: 'Receipt',
    account_name: 'GoPay Bersama',
    created_at: '2026-08-01T00:00:00Z',
    updated_at: '2026-08-01T00:00:00Z',
  },
];

export const DEMO_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-01',
    family_id: 'fam-bahagia-01',
    type: 'recurring_due',
    title: 'Tagihan Internet Rumah',
    message: 'Tagihan Internet Rumah (Rp 350.000) biasanya dibayar sekitar hari ini.',
    data: { recurring_id: 'rec-01', amount: 350000, description: 'Internet Rumah & Wifi Fiber' },
    is_read: false,
    action_url: '/catat?recurring=rec-01',
    created_at: new Date().toISOString(),
  },
  {
    id: 'notif-02',
    family_id: 'fam-bahagia-01',
    type: 'goal_milestone',
    title: 'Target Liburan Keluarga',
    message: 'Target Liburan Keluarga sudah mencapai 75%! Tinggal Rp 7,5 juta lagi menuju target.',
    data: { goal_id: 'goal-02', milestone: 75 },
    is_read: false,
    action_url: '/goal',
    created_at: new Date(Date.now() - 3600000 * 5).toISOString(),
  },
  {
    id: 'notif-03',
    family_id: 'fam-bahagia-01',
    type: 'budget_warning',
    title: 'Anggaran Makan & Minum 82%',
    message: 'Anggaran pos Makan & Minum sudah terpakai 82%. Sisa dana tersedia Rp 550.000.',
    data: { category_name: 'Makan & Minum', percentage: 82 },
    is_read: true,
    action_url: '/review',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];

export const DEFAULT_NOTIFICATION_PREFERENCES: NotificationPreferences = {
  budget_alerts: true,
  goal_milestones: true,
  recurring_reminders: true,
  unusual_alerts: true,
  family_activity: false,
};

export const DEMO_ACTIVITIES: FamilyActivityItem[] = [
  {
    id: 'act-01',
    family_id: 'fam-bahagia-01',
    actor_id: 'user-sinta-02',
    actor_name: 'Sinta Dewi',
    action_type: 'transaction_created',
    entity_type: 'transaction',
    entity_id: 'tx-02',
    title: 'Sinta mencatat belanja supermarket',
    description: 'Belanja mingguan beras, telur, minyak goreng — Rp 385.000',
    created_at: new Date(Date.now() - 3600000 * 3).toISOString(),
  },
  {
    id: 'act-02',
    family_id: 'fam-bahagia-01',
    actor_id: 'user-andi-01',
    actor_name: 'Andi Pratama',
    action_type: 'transfer_created',
    entity_type: 'transfer',
    entity_id: 'trf-01',
    title: 'Andi memindahkan dana',
    description: 'Transfer Rp 500.000 dari BCA Utama ke GoPay Bersama',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'act-03',
    family_id: 'fam-bahagia-01',
    actor_id: 'user-andi-01',
    actor_name: 'Andi Pratama',
    action_type: 'goal_updated',
    entity_type: 'goal',
    entity_id: 'goal-02',
    title: 'Andi menambah tabungan target',
    description: 'Setoran dana liburan +Rp 2.500.000 (mencapai 75%)',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
];

// ----------------------------------------------------------------------------
// Phase 4 Demo Data: Plans, Subscriptions, AI Usage & Financial Profile
// ----------------------------------------------------------------------------

export const DEMO_PLANS: Plan[] = [
  {
    id: 'plan-free',
    slug: 'free',
    name: 'LEGAKU Free',
    description: 'Pencatatan esensial keluarga dengan fitur dasar yang lengkap.',
    price_monthly: 0,
    price_yearly: 0,
    monthly_ai_limit: 15,
    monthly_receipt_limit: 5,
    monthly_voice_limit: 10,
    features: [
      'Pencatatan manual tanpa batas',
      'Kelola rekening & dompet',
      'Anggaran bulanan & target impian',
      'Review pengeluaran bulanan standar',
      '15x tanya LEGAKU AI per bulan',
      '5x scan foto struk per bulan',
    ],
    is_active: true,
  },
  {
    id: 'plan-plus',
    slug: 'plus',
    name: 'LEGAKU Plus',
    description: 'Kecerdasan finansial lanjutan untuk kenyamanan dan automasi keluarga.',
    price_monthly: 39000,
    price_yearly: 390000,
    monthly_ai_limit: 999999,
    monthly_receipt_limit: 60,
    monthly_voice_limit: 999999,
    features: [
      'Semua fitur Free',
      'Tanya LEGAKU AI tanpa batas',
      '60x scan foto struk AI per bulan',
      'Input suara tanpa batas',
      'Asesmen Financial Health Check',
      'Simulator Skenario Impian ("Coba Skenario")',
      'Ekspor Laporan PDF Siap Cetak & CSV',
    ],
    is_active: true,
  },
  {
    id: 'plan-family',
    slug: 'family',
    name: 'LEGAKU Family',
    description: 'Solusi lengkap kolaborasi multi-anggota untuk kebebasan finansial bersama.',
    price_monthly: 69000,
    price_yearly: 690000,
    monthly_ai_limit: 999999,
    monthly_receipt_limit: 150,
    monthly_voice_limit: 999999,
    features: [
      'Semua fitur Plus',
      'Hingga 5 anggota keluarga bersama',
      '150x scan foto struk per bulan',
      'Insight keuangan kolaboratif multi-peran',
      'Wawasan pola belanja cerdas keluarga',
      'Dukungan prioritas tim pengembang',
    ],
    is_active: true,
  },
  {
    id: 'plan-founder',
    slug: 'founder_lifetime',
    name: 'Founder Lifetime',
    description: 'Apresiasi eksklusif selamanya untuk pendukung mula-mula LEGAKU.',
    price_monthly: 0,
    price_yearly: 0,
    monthly_ai_limit: 999999,
    monthly_receipt_limit: 999999,
    monthly_voice_limit: 999999,
    features: [
      'Akses VIP seumur hidup tanpa batas',
      'Lencana Founder eksklusif',
      'Akses awal ke semua fitur masa depan',
      'Jalur komunikasi privat pengembang',
    ],
    is_active: true,
  },
];

export const DEMO_SUBSCRIPTION: Subscription = {
  id: 'sub-demo-01',
  user_id: 'user-andi-01',
  family_id: 'fam-bahagia-01',
  plan_slug: 'plus', // Active on Plus tier in demo mode
  status: 'active',
  started_at: '2026-08-01T00:00:00Z',
  expires_at: null,
  provider: 'internal',
  created_at: '2026-08-01T00:00:00Z',
  updated_at: '2026-08-01T00:00:00Z',
};

export const DEMO_FINANCIAL_PROFILE: FinancialProfile = {
  id: 'prof-bahagia-01',
  family_id: 'fam-bahagia-01',
  average_monthly_income: 26500000,
  average_monthly_expense: 5545000,
  average_savings_rate: 79,
  essential_expense_estimate: 4200000,
  emergency_fund_months: 4.8,
  common_spending_categories: [
    { name: 'Makan & Minum', percentage: 41 },
    { name: 'Rumah Tangga', percentage: 22 },
    { name: 'Transportasi', percentage: 18 },
    { name: 'Tagihan', percentage: 12 },
    { name: 'Hiburan', percentage: 7 },
  ],
  recurring_commitments: ['Internet Rumah (Rp 350.000)', 'Token Listrik (Rp 500.000)'],
  detected_patterns: [
    {
      id: 'pat-01',
      type: 'recurring_spending',
      title: 'Jadwal Tagihan Stabil',
      description: 'Tagihan internet dan listrik muncul rutin setiap minggu ke-4 dengan nominal yang konsisten.',
      confidence: 95,
      suggested_action: 'Manfaatkan fitur pengingat transaksi berulang agar tidak terlewat.',
    },
    {
      id: 'pat-02',
      type: 'savings_trend',
      title: 'Laju Tabungan Berkelanjutan',
      description: 'Selama 3 bulan terakhir, keluarga konsisten menyisihkan di atas 20% pemasukan untuk target bersama.',
      confidence: 92,
      suggested_action: 'Pertahankan alokasi ini untuk mempercepat target Liburan Keluarga.',
    },
    {
      id: 'pat-03',
      type: 'category_trend',
      title: 'Pola Belanja Rumah Tangga Terkendali',
      description: 'Pengeluaran supermarket cenderung terkonsentrasi di awal dan tengah bulan.',
      confidence: 88,
    },
  ],
  updated_at: '2026-09-20T00:00:00Z',
};

export const DEMO_AI_USAGE: AiUsageRecord[] = [
  {
    id: 'ai-use-01',
    user_id: 'user-andi-01',
    family_id: 'fam-bahagia-01',
    feature: 'companion',
    usage_date: new Date().toISOString().split('T')[0],
    request_count: 6,
  },
  {
    id: 'ai-use-02',
    user_id: 'user-andi-01',
    family_id: 'fam-bahagia-01',
    feature: 'receipt',
    usage_date: new Date().toISOString().split('T')[0],
    request_count: 2,
  },
  {
    id: 'ai-use-03',
    user_id: 'user-andi-01',
    family_id: 'fam-bahagia-01',
    feature: 'voice',
    usage_date: new Date().toISOString().split('T')[0],
    request_count: 3,
  },
];
